### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by pderksen** [sandhillsdevelopment/site#1]
Still `http://`

**Comment by pippinsplugins** [comment]
We should be able to get a Let's Encrypt certificate from Pagely now. I'll reach out.

**Comment by pippinsplugins** [comment]
I've requested access to self-service certificates so we can add this.

**Comment by gspice** [comment]
Got a few questions about this from promoting this site as a landing page for the BFCM sale (SSL)

**Comment by pippinsplugins** [comment]
Pagely is almost done upgrading our VPS to the new version that supports Lets Encrpyt. As soon as it's done, I'll be creating a certificate.
