### ISSUE TITLE
Remove Payouts Service from future projects

### ISSUE THREAD

**Issue by pippinsplugins** [sandhillsdevelopment/site#15]
Payouts Service is live!

It needs to be removed from this section: https://sandhillsdev.com/about/

Should it also have it's own dedicated entry on the Projects page?

**Comment by SeanChDavis** [comment]
Looks like I wasn't subscribed (or whatever) to this repo. My bad. 

I don't see a problem with it having its own entry there, but I want it to have its visual resources first. If we're treating it like a standalone product, I think it needs to be treated like other products. If it's a child of Alf, then I think it should be mentioned where Alf is mentioned.

**Comment by pippinsplugins** [comment]
I agree with that.

I'd like for us to try and get visual resources and branding together for it sometime in 2020.

**Comment by SeanChDavis** [comment]
@pippinsplugins Removed from future and added to 2019. All good?

EDIT: I've fixed the typo in the 2019 event.

![Screenshot_2019-11-30 About Us – Sandhills Development, LLC](https://user-images.githubusercontent.com/2359131/69904335-56a72380-135a-11ea-8531-a50c8b1f8785.png)

**Comment by pippinsplugins** [comment]
@SDavisMedia all good!
