### ISSUE TITLE
Suggestion: set list-style-position to outside

### ISSUE THREAD

**Issue by pippinsplugins** [sandhillsdevelopment/site#21]
Right now the `list-style-position` property is set to `inside`.

I personally think it looks a lot better when set to `outside`.

Compare `inside`:
![image](https://user-images.githubusercontent.com/1034109/71907734-3e34e080-3132-11ea-8f91-1c3a0ed2728a.png)
`Outside`:
![image](https://user-images.githubusercontent.com/1034109/71907755-4856df00-3132-11ea-8a33-f5ec1656c44b.png)

**Comment by SeanChDavis** [comment]
I can change that. 👍

**Comment by SeanChDavis** [comment]
Also going to use this issue to tweak more formatting. Phil pointed out an alignment issue with radio buttons. It's happening because of some Chrome-specific CSS that GF applied. Gonna fix that as well as any other formatting issues.
