### ISSUE TITLE
Style the subscription form

### ISSUE THREAD

**Issue by SeanChDavis** [sandhillsdevelopment/site#57]
Apparently, the site has a Subscribe page that I didn't create. That's weird because I always create one. I can't remember why I wouldn't, other than, perhaps, there was no specific email list to sign up to. Maybe I just missed a page when designing the site. I don't know. After Drew asked me about subscribing, I checked my normal URL and found this:

<img width="693" alt="Screenshot 2021-02-02 195824" src="https://user-images.githubusercontent.com/2359131/106687095-1b713780-6591-11eb-8134-0d90c2c8a8e3.png">

Ummmmm yeeeeeaaaaah I'm gonna fix that up.

**Comment by pippinsplugins** [comment]
Yikes!

**Comment by SeanChDavis** [comment]
@pippinsplugins Is there a list specifically for SHD blog? Or is this supposed to serve as just a way to sign up for the other blogs? In other words, what exactly do we want here?

**Comment by pippinsplugins** [comment]
There's no set audience. We're just using the whole list for that blog.

I don't think this page should show anything except for an email sign up that puts them on the main list without defining any interests.

The product groups get populated by purchases and the signup forms on each of those sites.

**Comment by SeanChDavis** [comment]
Good deal. I'll start working on it tomorrow. I'll ping someone in marketing to make sure I'm taking the preferred approach.

**Comment by SeanChDavis** [comment]
This is fixed. I added GF Mailchimp Add-on to the site and set up a new form. That new form replaced the old one. Form submission is tested and working as expected in Mailchimp. https://sandhillsdev.com/subscribe/
