### ISSUE TITLE
Remove mentions of Sellbird from the site

### ISSUE THREAD

**Issue by lisag** [sandhillsdevelopment/site#67]
Since Sellbird is no longer an active project we should remove some mentions of it from the website, such as on the Front page and on the Projects page.

**Comment by SeanChDavis** [comment]
@lisag Gladly. It would also be a good time to add Payouts Service. To do that, I'd need copy for the front page section that would show (one short sentence) and for the Projects page (a paragraph or two).

**Comment by SeanChDavis** [comment]
Sellbird removed.

**Comment by pippinsplugins** [comment]
@SDavisMedia yes sir!

**Comment by SeanChDavis** [comment]
Closing for #68
