### ISSUE TITLE
Subscribe page/form subheading update

### ISSUE THREAD

**Issue by pderksen** [sandhillsdevelopment/site#71]
Please update the `/subscribe/` page/form subheading to the following (assuming it's in the template):

Stay up to date with Sandhills Development news and special promotions.

This replaces the line "Enter your email and name below"

**Comment by SeanChDavis** [comment]
Nope, just an entry on the page edit screen. Updated.

**Comment by pderksen** [comment]
Ah I see it now down the page edit screen.
