### ISSUE TITLE
Update site and project details

### ISSUE THREAD

**Issue by SeanChDavis** [sandhillsdevelopment/site#76]
Just making sure all site. company, and project details are up-to-date.

**Comment by SeanChDavis** [comment]
I can't push to the repo, but this is mostly done minus the ACF content edits that need to be done on the site itself.

**Comment by pippinsplugins** [comment]
@SDavisMedia can you push up the changes to a branch? With a PR I can take care of the deployment.

**Comment by pippinsplugins** [comment]
@SDavisMedia I have re-added you to this repo.

**Comment by SeanChDavis** [comment]
@pippinsplugins Auto deployment failed on staging and will probably fail live too. But that's the only thing blocking the PR. https://github.com/sandhillsdevelopment/site/pull/77

**Comment by SeanChDavis** [comment]
@pippinsplugins Okay so I just finished reworking the entire Projects system so that it makes more sense for the current state of Projects, and how it sounds like you will use them in the future. It's probably best we hop on a call again to walk through it. This includes making sure the single Project page is designed to be used, by the way.

One more Zoom and this'll be good to go. Sooner than later is better so I can pack up my PC.
